name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリチェックアウト
        uses: actions/checkout@v4

      - name: JDKセットアップ
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Mavenビルドとテスト実行
        run: mvn clean install
