name: CI/CD

on:
  push:
    branches:
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: cicd
        ports:
          - 5432:5432
        

    steps:
      - name: リポジトリチェックアウト
        uses: actions/checkout@v4

      - name: JDK17セットアップ
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Mavenでテスト実行
        run: mvn test
