name: CI/CD

on:
  push:
    branches:
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリチェックアウト
        uses: actions/checkout@v4

      - name: JDK17セットアップ
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Mavenでテスト実行
        run: mvn test
